// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbA3D2e_iHJhWI2UIkYYsh_jSrQesbIM',
    appId: '1:146064547814:ios:e44c4b7f7c4b2d277dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
    iosBundleId: 'com.example.drawoApp',
  );
}
