// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6YsnCDGlBWBJNnq-F1StC7wxqMn1mmlQ',
    appId: '1:146064547814:web:135acec9470bd91a7dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    authDomain: 'drawing-app-e7cd3.firebaseapp.com',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
    measurementId: 'G-XG1WJPW4MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFKcYWpIPxd4dxn1x3TOxanNhITRNb8w',
    appId: '1:146064547814:android:bd22b3564170d2487dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbA3D2e_iHJhWI2UIkYYsh_jSrQesbIM',
    appId: '1:146064547814:ios:e44c4b7f7c4b2d277dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
    iosBundleId: 'com.example.drawoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWbA3D2e_iHJhWI2UIkYYsh_jSrQesbIM',
    appId: '1:146064547814:ios:e44c4b7f7c4b2d277dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
    iosBundleId: 'com.example.drawoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6YsnCDGlBWBJNnq-F1StC7wxqMn1mmlQ',
    appId: '1:146064547814:web:3333a62a9a62aeb37dc027',
    messagingSenderId: '146064547814',
    projectId: 'drawing-app-e7cd3',
    authDomain: 'drawing-app-e7cd3.firebaseapp.com',
    storageBucket: 'drawing-app-e7cd3.firebasestorage.app',
    measurementId: 'G-5JG9ND7348',
  );
}
